default:
  title: Outpost
buckinghamshire:
  title: Manage directory listing
  directories:
    - value: Family Information Service
      label: bfis
    - value: Buckinghamshire Online Directory
      label: bod