default:
  title: Outpost
buckinghamshire:
  title: Manage service listing
  directories:
    - name: FIS
      value: Family Information Service
    - name: BOD
      value: Buckinghamshire Online Directory